version: "3"

services:

  runtime-setup:
    image: netty-tcnative-debian:debian-11-1.8
    build:
      args:
        debian_version : "11"
        java_version : "8.0.412-zulu"
        openssl_version : "3.0.9"

  deploy-dynamic-only:
    image: netty-tcnative-debian:debian-11-1.8

  stage-snapshot:
    image: netty-tcnative-debian:debian-11-1.8

  stage-release:
    image: netty-tcnative-debian:debian-11-1.8

  build-dynamic-only:
    image: netty-tcnative-debian:debian-11-1.8

  build:
    image: netty-tcnative-debian:debian-11-1.8

  shell:
    image: netty-tcnative-debian:debian-11-1.8
